// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetQuotaData() {
  return window['go']['main']['App']['GetQuotaData']();
}

export function IsAutoStart() {
  return window['go']['main']['App']['IsAutoStart']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function RefreshNow() {
  return window['go']['main']['App']['RefreshNow']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveWindowWidth(arg1) {
  return window['go']['main']['App']['SaveWindowWidth'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}
