// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetQuotaData():Promise<main.QuotaMonitorData>;

export function IsAutoStart():Promise<boolean>;

export function LoadConfig():Promise<main.AppConfig>;

export function RefreshNow():Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SaveWindowWidth(arg1:number):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;
